In [1]:
import pandas as pd

## Read a .csv from a URL with Pandas
Target website: https://www.football-data.co.uk/data.php

In [3]:
df = pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

In [4]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [5]:
root = "https://www.football-data.co.uk/mmz4281/"

In [ ]:
# creating list of leagues
leagues = ['E0','E1','E2', 'E3','EC']

frames = []
# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/"  + league + ".csv")
    frames.append(df)

In [7]:
len(frames)

4

In [14]:
# Merge all DataFrames into one DataFrame
Faizan = pd.concat(frames, ignore_index=True)

In [15]:
Faizan

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86,NaN
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86,NaN
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08,NaN
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97,NaN
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2031,E3,02/05/2026,15:00,Harrogate,Barnet,1,2,A,1,1,...,1.73,NaN,NaN,2.08,1.80,1.99,1.73,NaN,NaN,NaN
2032,E3,02/05/2026,15:00,Notts County,Bristol Rvs,1,1,D,1,0,...,1.93,NaN,NaN,1.93,1.93,1.86,1.86,NaN,NaN,NaN
2033,E3,02/05/2026,15:00,Oldham,Accrington,3,0,H,1,0,...,1.88,NaN,NaN,1.98,1.88,1.84,1.87,NaN,NaN,NaN
2034,E3,02/05/2026,15:00,Swindon,Chesterfield,1,2,A,1,1,...,1.83,NaN,NaN,2.03,1.83,1.96,1.77,NaN,NaN,NaN
2035,E3,02/05/2026,15:00,Tranmere,Grimsby,1,1,D,0,1,...,1.95,NaN,NaN,1.90,1.95,1.87,1.85,NaN,NaN,NaN

In [18]:
# Save to CSV
Faizan.to_csv("2025-26 data.xlsx", index=False)

In [24]:
leagues = ['E0','E2', 'E3']

frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15,21): # range of seasons
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
#         df['season'] = season
        
        frames.append(df)

In [25]:
len(frames)

18

In [26]:
# Merge all DataFrames into one DataFrame
Faizan = pd.concat(frames, ignore_index=True)

In [27]:
Faizan

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,08/08/2015,Bournemouth,Aston Villa,0.0,1.0,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,08/08/2015,Chelsea,Swansea,2.0,2.0,D,2.0,1.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,08/08/2015,Everton,Watford,2.0,2.0,D,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,08/08/2015,Leicester,Sunderland,4.0,2.0,H,3.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,08/08/2015,Man United,Tottenham,1.0,0.0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8637,E3,08/05/2021,Port Vale,Mansfield,0.0,3.0,A,0.0,2.0,A,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
8638,E3,08/05/2021,Scunthorpe,Stevenage,0.0,1.0,A,0.0,0.0,D,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
8639,E3,08/05/2021,Southend,Newport County,1.0,1.0,D,1.0,0.0,H,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
8640,E3,08/05/2021,Tranmere,Colchester,0.0,0.0,D,0.0,0.0,D,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
8641,E3,08/05/2021,Salford,Leyton Orient,3.0,0.0,H,1.0,0.0,H,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [30]:
leagues = ['E0','E1','E2', 'E3','EC']

frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15,26): # range of seasons
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv", encoding='latin1')
        frames.append(df)

In [31]:
len(frames)

55

In [32]:
Faizan = pd.concat(frames, ignore_index=True)

In [33]:
Faizan

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA,Unnamed: 132
0,E0,08/08/2015,Bournemouth,Aston Villa,0.0,1.0,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,08/08/2015,Chelsea,Swansea,2.0,2.0,D,2.0,1.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,08/08/2015,Everton,Watford,2.0,2.0,D,0.0,1.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,08/08/2015,Leicester,Sunderland,4.0,2.0,H,3.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,08/08/2015,Man United,Tottenham,1.0,0.0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27979,NaN,25/04/2026,Scunthorpe,Eastleigh,0.0,1.0,A,0.0,1.0,A,...,1.65,3.9,4.33,NaN,NaN,NaN,1.67,3.75,3.90,NaN
27980,NaN,25/04/2026,Southend,Wealdstone,2.0,1.0,H,2.0,1.0,H,...,1.50,4.2,5.25,NaN,NaN,NaN,1.48,4.20,5.00,NaN
27981,NaN,25/04/2026,Tamworth,Braintree Town,5.0,1.0,H,2.0,1.0,H,...,1.45,4.5,5.50,NaN,NaN,NaN,1.50,4.20,4.60,NaN
27982,NaN,25/04/2026,Woking,Halifax,0.0,1.0,A,0.0,0.0,D,...,2.30,3.3,2.80,NaN,NaN,NaN,2.20,3.25,2.80,NaN
27983,NaN,25/04/2026,Yeovil,Solihull,1.0,4.0,A,1.0,4.0,A,...,2.88,3.3,2.25,NaN,NaN,NaN,2.75,3.20,2.25,NaN